[package]
name = "swissrpg-app"
version = "0.1.0"
authors = ["Daniel Thul <daniel.thul@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
# bottest feature not enabled by default
default = []

bottest = ["lib/bottest", "ui/bottest"]

[dependencies]
lib = { path = "../lib", package = "swissrpg-lib" }
ui = { path = "../ui", package = "swissrpg-ui" }
futures = "0.3"
futures-channel = "0.3"
futures-util = { version = "0.3", features = ["compat"] }
redis = "0.12"
serenity = "0.7"
tokio = { version = "0.2", default-features = false, features = ["rt-threaded", "time"] }
white_rabbit = "0.1"
