[package]
name = "swissrpg-app"
version = "0.1.0"
authors = ["Daniel Thul <daniel.thul@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
# bottest feature not enabled by default
default = []

bottest = ["lib/bottest", "ui/bottest"]

[dependencies]
lib = { path = "../lib", package = "swissrpg-lib" }
ui = { path = "../ui", package = "swissrpg-ui" }
futures = "0.3"
futures-channel = "0.3"
futures-util = "0.3"
redis = { version = "0.17", default-features = false, features = ["tokio-comp"] }
serenity = { version = "0.9", default-features = false, features = ["cache", "client", "gateway", "model", "rustls_backend"] }
signal-hook = "0.1"
stripe-rust = { git = "https://github.com/wyyerd/stripe-rs", rev = "1a1798860da5d246f556097d2d37eef44907fb6d", default-features = false, features = ["billing", "webhook-events", "rustls-tls"] }
tokio = { version = "0.2", default-features = false, features = ["io-driver", "rt-threaded", "time"] }
