[package]
name = "swissrpg-ui"
version = "0.1.0"
authors = ["Daniel Thul <daniel.thul@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
# bottest feature not enabled by default
default = []

bottest = ["lib/bottest"]

[dependencies]
lib = { path = "../lib", package = "swissrpg-lib" }
aho-corasick = "0.7"
command_macro = { path = "../command_macro", package = "swissrpg-command-macro" }
askama = "0.9"
assert-impl = "0.1"
bytes = "0.5"
chrono = "0.4"
chrono-tz = "0.5"
cookie = "0.14"
futures = "0.3"
futures-channel = "0.3"
futures-util = "0.3"
hyper = "0.13"
num-traits = "0.2"
oauth2 = "4.0.0-alpha.1"
once_cell = "1.4"
rand = "0.7"
redis = { version = "0.16", default-features = false, features = ["tokio-comp"] }
regex = "1"
serde = "1.0"
serde_json = "1.0"
serenity = { version = "0.9.0-rc.1", default-features = false, features = ["cache", "client", "gateway", "model", "rustls_backend"] }
simple-error = "0.2"
stripe-rust = { git = "https://github.com/wyyerd/stripe-rs", rev = "1a1798860da5d246f556097d2d37eef44907fb6d", default-features = false, features = ["billing", "webhook-events", "rustls-tls"] }
time = "0.2"
tokio = { version = "0.2", default-features = false, features = ["rt-threaded", "time"] }
warp = "0.2"
