[package]
name = "swissrpg-ui"
version = "0.1.0"
authors = ["Daniel Thul <daniel.thul@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
# bottest feature not enabled by default
default = []

bottest = ["lib/bottest"]

[dependencies]
lib = { path = "../lib", package = "swissrpg-lib" }
askama = "0.8"
backtrace = "0.3"
base64 = "0.10"
chrono = "0.4"
cookie = "0.12"
failure = "0.1" # Just for oauth2 reqwest async client
failure_derive = "0.1" # Just for oauth2 reqwest async client
futures_01 = { version = "0.1", package = "futures" } # Just for oauth2 reqwest async client
futures-channel-preview = "0.3.0-alpha.19"
futures-preview = "0.3.0-alpha.19"
futures-util-preview = { version = "0.3.0-alpha.19", features = ["compat"] }
http = "0.1" # Just for oauth2 reqwest async client
hyper = "0.13.0-alpha.4"
itertools = "0.8"
lazy_static = "1.4"
oauth2 = { version = "=3.0.0-alpha.4", default-features = false }
rand = "0.7"
redis = "0.12"
regex = "1"
reqwest = { version = "0.10.0-alpha.2", features = ["blocking", "json"] }
serde = "1.0"
serde_json = "1.0"
serenity = "0.7"
simple-error = "0.2"
time = "0.1"
tokio = { version = "0.2.0-alpha.6", default-features = false, features = ["rt-full"] }
url = "2.1"
white_rabbit = "0.1"
