[package]
name = "swissrpg-ui"
version = "0.1.0"
authors = ["Daniel Thul <daniel.thul@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
# bottest feature not enabled by default
default = []

bottest = ["lib/bottest"]

[dependencies]
lib = { path = "../lib", package = "swissrpg-lib" }
askama = "0.8"
chrono = "0.4"
chrono-tz = "0.5"
cookie = "0.12"
futures = "0.3"
futures-channel = "0.3"
futures-util = { version = "0.3", features = ["compat"] }
hyper = "0.13"
num-traits = "0.2"
oauth2 = { version = "3.0.0-alpha.7", default-features = false, features = ["futures-03"] }
rand = "0.7"
redis = "0.12"
regex = "1"
serde = "1.0"
serde_json = "1.0"
serenity = "0.7"
simple-error = "0.2"
time = "0.1"
tokio = { version = "0.2", default-features = false, features = ["rt-threaded", "time"] }
warp = { git = "https://github.com/seanmonstar/warp", rev = "b6cbcca0914cfb435ae19c1aab86c0ffa0316322" }
white_rabbit = "0.1"
